### ISSUE TITLE
Make fault tolerant

### ISSUE THREAD

**Issue by Divide-By-0** [zkemail/zk-regex-registry#44]
We frequently have failures like this, on totally fine patterns, that should trigger re-compilation:
```
[4/4] Building fresh packages...
[circuit-compile] 2024-10-16T16:49:53.509Z - 
[circuit-compile] 2024-10-16T16:49:53.902Z - success Saved lockfile.
[circuit-compile] 2024-10-16T16:49:53.902Z - 
[circuit-compile] 2024-10-16T16:49:53.932Z - Done in 30.18s.
[circuit-compile] 2024-10-16T16:49:53.932Z - 
[circuit-compile] 2024-10-16T16:51:58.624Z - template instances: 265
[circuit-compile] 2024-10-16T16:51:58.624Z - 
[circuit-compile] 2024-10-16T16:55:27.399Z - Traceback (most recent call last):
[circuit-compile] 2024-10-16T16:55:27.399Z - 
[circuit-compile] 2024-10-16T16:55:27.435Z -   File "/pkg/modal/_container_io_manager.py", line 733, in handle_input_exception
[circuit-compile] 2024-10-16T16:55:27.435Z -     yield
[circuit-compile] 2024-10-16T16:55:27.435Z -   File "/pkg/modal/_container_entrypoint.py", line 382, in run_input_sync
[circuit-compile] 2024-10-16T16:55:27.435Z -     res = io_context.call_finalized_function()
[circuit-compile] 2024-10-16T16:55:27.435Z -           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[circuit-compile] 2024-10-16T16:55:27.435Z - 
[circuit-compile] 2024-10-16T16:55:27.435Z -   File "/pkg/modal/_container_io_manager.py", line 166, in call_finalized_function
[circuit-compile] 2024-10-16T16:55:27.435Z -     res = self.finalized_function.callable(*args, **kwargs)
[circuit-compile] 2024-10-16T16:55:27.435Z -           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[circuit-compile] 2024-10-16T16:55:27.435Z -   File "/root/compile-circuit.py", line 42, in compile_circuit
[circuit-compile] 2024-10-16T16:55:27.435Z -     subprocess.run(["circom", circuitPath, "--r1cs", "--wasm", "-o", f"/temp_output/{slug}", "-l", "/project/node_modules"], check=True)
[circuit-compile] 2024-10-16T16:55:27.435Z -   File "/usr/local/lib/python3.11/subprocess.py", line 571, in run
[circuit-compile] 2024-10-16T16:55:27.435Z -     raise CalledProcessError(retcode, process.args,
[circuit-compile] 2024-10-16T16:55:27.435Z - 
[circuit-compile] 2024-10-16T16:55:27.435Z - subprocess.CalledProcessError: Command '['circom', '/project/circuit/devcon_rejection.circom', '--r1cs', '--wasm', '-o', '/temp_output/saugardev/devcon-rejection-proof', '-l', '/project/node_modules']' died with <Signals.SIGSEGV: 11>.
[circuit-compile] 2024-10-16T16:55:27.435Z - 
[circuit-compile] 2024-10-16T16:55:28.520Z - ╭───────────────────── Traceback (most recent call last) ──────────────────────╮
[circuit-compile] 2024-10-16T16:55:28.520Z - │ /home/sdk/zk-regex-registry/packages/app/modal/compile-circuit.py:17 in main │
[circuit-compile] 2024-10-16T16:55:28.520Z - │                                                                              │
[circuit-compile] 2024-10-16T16:55:28.520Z - │   16 │   slug = os.environ["PROJECT_SLUG"]                                   │
[circuit-compile] 2024-10-16T16:55:28.520Z - │ ❱ 17 │   compile_circuit.remote(slug)                                        │
[circuit-compile] 2024-10-16T16:55:28.520Z - │   18                                                                         │
[circuit-compile] 2024-10-16T16:55:28.520Z - │                                                                              │
[circuit-compile] 2024-10-16T16:55:28.520Z - │     ...Remote call to Modal Function (ta-01JAB3QNY9DE2QKY3M8RTWFPFC)...      │
[circuit-compile] 2024-10-16T16:55:28.520Z - │                                                                              │
[circuit-compile] 2024-10-16T16:55:28.520Z - │ /root/compile-circuit.py:42 in compile_circuit                               │
[circuit-compile] 2024-10-16T16:55:28.520Z - │                                                                              │
[circuit-compile] 2024-10-16T16:55:28.520Z - │ ❱ 42 subprocess.run(["circom", circuitPath, "--r1cs", "--wasm", "-o", f"/tem │
[circuit-compile] 2024-10-16T16:55:28.520Z - │                                                                              │
[circuit-compile] 2024-10-16T16:55:28.520Z - │                                                                              │
[circuit-compile] 2024-10-16T16:55:28.520Z - │ /usr/local/lib/python3.11/subprocess.py:571 in run                           │
[circuit-compile] 2024-10-16T16:55:28.520Z - │                                                                              │
[circuit-compile] 2024-10-16T16:55:28.520Z - │ ❱ 571 raise CalledProcessError(retcode, process.args,                        │
[circuit-compile] 2024-10-16T16:55:28.520Z - │                                                                              │
[circuit-compile] 2024-10-16T16:55:28.520Z - ╰──────────────────────────────────────────────────────────────────────────────╯
[circuit-compile] 2024-10-16T16:55:28.520Z - CalledProcessError: Command '['circom', 
[circuit-compile] 2024-10-16T16:55:28.520Z - '/project/circuit/devcon_rejection.circom', '--r1cs', '--wasm', '-o', 
[circuit-compile] 2024-10-16T16:55:28.520Z - '/temp_output/saugardev/devcon-rejection-proof', '-l', '/project/node_modules']'
[circuit-compile] 2024-10-16T16:55:28.520Z - died with <Signals.SIGSEGV: 11>.
[circuit-compile] 2024-10-16T16:55:28.520Z - 
[circuit-compile] 2024-10-16T16:55:28.743Z - Process exited with code 1
```

**Comment by javiersuweijie** [comment]
Checks if the logs have clues on whether the build can be restarted, restart if there are.
